#!/usr/bin/env bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${SCRIPT_DIR}"

for dir in */; do
	if [ -f "${dir}/_make" ]; then
		echo "Running _make in ${dir}"
		./"${dir}/_make"
	fi
done
