#!/usr/bin/env bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${SCRIPT_DIR}"
DEMO_DIR="${DEMO_DIR:-"${PWD//demo_templates\//demos\/}"}/"

rm -rf "${DEMO_DIR}"
mkdir -p "${DEMO_DIR}"

cp ./*.py "${DEMO_DIR}"
