name: Build Report

on:
  push:
    paths:
      - report/**
      - .github/workflows/report.yml
  workflow_dispatch:

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - name: Install pandoc filters
        run: pip install -r requirements.txt
        working-directory: report
      - run: make tex
        working-directory: report
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
          working_directory: report
      - uses: actions/upload-artifact@master
        with:
          name: report.pdf
          path: report/report.pdf
      - run: mkdir -p build && mv report/report.pdf build/
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
